spring:
    view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp
    social:
        facebook:
            appId: 381421658930345
            appSecret: be7a30c508c455c523485de8f43c5de8

#    jpa:
#        database: H2


#    datasource:
#        url: jdbc:h2:mem:mydb
#        username: sa
#        password: sa
#        driverClassName: org.h2.jdbcx.JdbcDataSource
#        platform: h2

        